branches:
  only:
  - master
language: python
python:
- 3.7
install:
- pip install -r requirements.txt
script:
- pelican content
notifications:
  email:
    on_success: always
    on_failure: always

before_install:
- git submodule update --init --recursive
after_success: bash deploy.sh
