branches:
  only:
  - master
language: python
python:
- 3.7
install:
- pip install -r requirements.txt
script:
- pelican content
notifications:
  email:
    on_success: always
    on_failure: always
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: output
  on:
    branch: master
before_install:
- git submodule update --init --recursive
after_success: bash deploy.sh
